## Data Analysis

In [130]:
import pandas as pd

dataset = pd.read_csv("Teen_Mental_Health_Dataset.csv")
dataset.head()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0

In [131]:
dataset.shape

(1200, 13)

In [132]:
dataset.isna().sum()

age                         0
gender                      0
daily_social_media_hours    0
platform_usage              0
sleep_hours                 0
screen_time_before_sleep    0
academic_performance        0
physical_activity           0
social_interaction_level    0
stress_level                0
anxiety_level               0
addiction_level             0
depression_label            0
dtype: int64

In [133]:
dataset.dtypes

age                           int64
gender                       object
daily_social_media_hours    float64
platform_usage               object
sleep_hours                 float64
screen_time_before_sleep    float64
academic_performance        float64
physical_activity           float64
social_interaction_level     object
stress_level                  int64
anxiety_level                 int64
addiction_level               int64
depression_label              int64
dtype: object

In [134]:
dataset.gender.unique()

array(['male', 'female'], dtype=object)

In [135]:
dataset.platform_usage.unique()

array(['Instagram', 'TikTok', 'Both'], dtype=object)

In [136]:
dataset.social_interaction_level.unique()

array(['low', 'high', 'medium'], dtype=object)

In [137]:
from sklearn.preprocessing import OneHotEncoder

categorical_cols = ["gender", "platform_usage", "social_interaction_level"]

encoder = OneHotEncoder(drop="first", sparse_output=False)

In [138]:
encoded_data = encoder.fit_transform(dataset[categorical_cols])

In [139]:
encoded_df = pd.DataFrame(
    encoded_data,
    columns=encoder.get_feature_names_out(categorical_cols)
)

encoded_df.index = dataset.index

dataset = dataset.drop(categorical_cols, axis=1)
dataset = pd.concat([dataset, encoded_df], axis=1)

In [140]:
dataset.head()

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,depression_label,gender_male,platform_usage_Instagram,platform_usage_TikTok,social_interaction_level_low,social_interaction_level_medium
0,14,7.9,7.4,2.9,3.01,1.5,2,2,1,0,1.0,1.0,0.0,1.0,0.0
1,19,1.9,8.0,2.9,3.22,0.8,8,1,10,0,0.0,0.0,1.0,0.0,0.0
2,17,1.3,7.6,0.5,3.92,0.0,2,4,2,0,0.0,1.0,0.0,0.0,0.0
3,15,7.4,6.9,1.6,3.48,0.8,1,7,9,0,1.0,0.0,1.0,0.0,1.0
4,15,4.7,4.9,3.0,2.37,1.4,3,5,2,0,0.0,0.0,0.0,0.0,1.0

In [141]:
dataset.shape

(1200, 15)

In [142]:
dataset.describe()

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,depression_label,gender_male,platform_usage_Instagram,platform_usage_TikTok,social_interaction_level_low,social_interaction_level_medium
count,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000
mean,15.928333,4.536667,6.449417,1.740333,2.990383,1.014500,5.445833,5.636667,5.565000,0.025833,0.512500,0.342500,0.331667,0.345833,0.346667
std,2.021947,2.029599,1.442677,0.716660,0.576758,0.582185,2.903290,2.859453,2.830627,0.158704,0.500052,0.474744,0.471008,0.475837,0.476107
min,13.000000,1.000000,4.000000,0.500000,2.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,14.000000,2.800000,5.200000,1.100000,2.500000,0.500000,3.000000,3.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,16.000000,4.500000,6.500000,1.800000,2.990000,1.000000,5.000000,6.000000,6.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
75%,18.000000,6.300000,7.600000,2.400000,3.480000,1.500000,8.000000,8.000000,8.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,19.000000,8.000000,9.000000,3.000000,4.000000,2.000000,10.000000,10.000000,10.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [143]:
dataset.depression_label.value_counts()

depression_label
0    1169
1      31
Name: count, dtype: int64

#### Good Features

In [144]:
good_features = [
    "age",
    "daily_social_media_hours",
    "sleep_hours",
    "screen_time_before_sleep",
    "academic_performance",
    "physical_activity",
    "gender_male",
    "platform_usage_Instagram",
    "platform_usage_TikTok",
    "social_interaction_level_low",
    "social_interaction_level_medium"
]

In [145]:
from sklearn.model_selection import train_test_split

X = dataset[good_features]
y = dataset.depression_label

x_train, x_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [146]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

## Model Training

### Logistic Regression

In [147]:
from sklearn.linear_model import LogisticRegression

lg = LogisticRegression(class_weight="balanced")
lg.fit(x_train_scaled, y_train)

LogisticRegression(class_weight='balanced')

In [148]:
from sklearn.metrics import confusion_matrix

y_pred = lg.predict(x_test_scaled)
print(confusion_matrix(y_test, y_pred))

[[205  29]
 [  2   4]]

In [149]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.88      0.93       234
           1       0.12      0.67      0.21         6

    accuracy                           0.87       240
   macro avg       0.56      0.77      0.57       240
weighted avg       0.97      0.87      0.91       240

In [150]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test, y_pred))

0.8708333333333333

### Random Forest Classifier

In [151]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rfc.fit(x_train_scaled, y_train)

RandomForestClassifier(random_state=42)

In [152]:
from sklearn.metrics import confusion_matrix

y_pred = rfc.predict(x_test_scaled)
print(confusion_matrix(y_test, y_pred))

[[234   0]
 [  6   0]]

In [153]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      1.00      0.99       234
           1       0.00      0.00      0.00         6

    accuracy                           0.97       240
   macro avg       0.49      0.50      0.49       240
weighted avg       0.95      0.97      0.96       240

C:\Users\H A Traders\miniconda3\envs\py311\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\H A Traders\miniconda3\envs\py311\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\H A Traders\miniconda3\envs\py311\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

### Decision Tree Classifier

In [154]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()

dt.fit(x_train_scaled, y_train)

DecisionTreeClassifier()

In [155]:
from sklearn.metrics import confusion_matrix

y_pred = dt.predict(x_test_scaled)
print(confusion_matrix(y_test, y_pred))

[[226   8]
 [  5   1]]

In [156]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.97      0.97       234
           1       0.11      0.17      0.13         6

    accuracy                           0.95       240
   macro avg       0.54      0.57      0.55       240
weighted avg       0.96      0.95      0.95       240

### Extreme Gradient Boosting

In [157]:
from xgboost import XGBClassifier

xgb = XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=4,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric='logloss'
)

xgb.fit(x_train_scaled, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

In [158]:
from sklearn.metrics import confusion_matrix

y_pred = xgb.predict(x_test_scaled)
print(confusion_matrix(y_test, y_pred))

[[233   1]
 [  6   0]]

In [159]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      1.00      0.99       234
           1       0.00      0.00      0.00         6

    accuracy                           0.97       240
   macro avg       0.49      0.50      0.49       240
weighted avg       0.95      0.97      0.96       240

## Export Model

In [160]:
import joblib

In [161]:
import joblib

joblib.dump(good_features, "features.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(lg, "logistic_model.pkl")

['logistic_model.pkl']

In [162]:
model = joblib.load("logistic_model.pkl")
scaler = joblib.load("scaler.pkl")
features = joblib.load("features.pkl")

print(type(model))
print(type(scaler))
print(features)

<class 'sklearn.linear_model._logistic.LogisticRegression'>
<class 'sklearn.preprocessing._data.StandardScaler'>
['age', 'daily_social_media_hours', 'sleep_hours', 'screen_time_before_sleep', 'academic_performance', 'physical_activity', 'gender_male', 'platform_usage_Instagram', 'platform_usage_TikTok', 'social_interaction_level_low', 'social_interaction_level_medium']